import React, { useState } from 'react';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { chatWithAI } from '../services/api';

const STUDENTS = [
  {id:'STU-001',name:'Aisha Rahman', initials:'AR',cls:'Class 8-A',roll:'01',att:95,avBg:'#1E3A5F',avColor:'#3B82F6',generated:false,comment:null,principalComment:null,
   results:[{sub:'English',marks:82,full:100,grade:'A+'},{sub:'Mathematics',marks:74,full:100,grade:'A'},{sub:'Science',marks:69,full:100,grade:'B'},{sub:'Bengali',marks:78,full:100,grade:'A'},{sub:'Social Studies',marks:85,full:100,grade:'A+'}]},
  {id:'STU-002',name:'Karim Ahmed',  initials:'KA',cls:'Class 9-B',roll:'05',att:78,avBg:'#451A03',avColor:'#F59E0B',generated:false,comment:null,principalComment:null,
   results:[{sub:'English',marks:65,full:100,grade:'B'},{sub:'Mathematics',marks:58,full:100,grade:'C'},{sub:'Science',marks:71,full:100,grade:'A'},{sub:'Bengali',marks:60,full:100,grade:'B'},{sub:'Social Studies',marks:55,full:100,grade:'C'}]},
  {id:'STU-003',name:'Fatema Begum', initials:'FB',cls:'Class 7-A',roll:'03',att:61,avBg:'#450A0A',avColor:'#EF4444',generated:false,comment:null,principalComment:null,
   results:[{sub:'English',marks:45,full:100,grade:'C'},{sub:'Mathematics',marks:38,full:100,grade:'D'},{sub:'Science',marks:50,full:100,grade:'C'},{sub:'Bengali',marks:42,full:100,grade:'C'},{sub:'Social Studies',marks:48,full:100,grade:'C'}]},
  {id:'STU-004',name:'Mehedi Islam', initials:'MI',cls:'Class 6-B',roll:'02',att:92,avBg:'#2E1065',avColor:'#8B5CF6',generated:false,comment:null,principalComment:null,
   results:[{sub:'English',marks:88,full:100,grade:'A+'},{sub:'Mathematics',marks:91,full:100,grade:'A+'},{sub:'Science',marks:85,full:100,grade:'A+'},{sub:'Bengali',marks:82,full:100,grade:'A+'},{sub:'Social Studies',marks:90,full:100,grade:'A+'}]},
];


function exportToPDF(student, avg, overallGrade) {
  const doc = new jsPDF();
  
  // Header
  doc.setFillColor(30, 58, 95);
  doc.rect(0, 0, 210, 35, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.text('LAKEFIELD GLOBAL SCHOOL', 14, 12);
  doc.setFontSize(16);
  doc.text('Student Report Card', 14, 22);
  doc.setFontSize(10);
  doc.text('Term 2 - Academic Year 2025-2026', 14, 30);

  // Student info
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  let y = 45;
  doc.text(`Student Name: ${student.name}`, 14, y);
  doc.text(`Class: ${student.cls}`, 120, y);
  y += 7;
  doc.text(`Roll Number: ${student.roll}`, 14, y);
  doc.text(`Student ID: ${student.id}`, 120, y);
  y += 7;
  doc.text(`Attendance: ${student.att}%`, 14, y);
  doc.text(`Overall Grade: ${overallGrade} (${avg}%)`, 120, y);

  // Results table
  y += 12;
  const tableData = student.results.map(r => [
    r.sub, `${r.marks}/${r.full}`, `${Math.round(r.marks/r.full*100)}%`, r.grade, r.marks >= 33 ? 'Pass' : 'Fail'
  ]);

  doc.autoTable({
    startY: y,
    head: [['Subject', 'Marks', '%', 'Grade', 'Result']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [30, 58, 95] },
    margin: { left: 14, right: 14 },
  });

  let finalY = doc.lastAutoTable.finalY + 10;

  // Teacher comment
  if (student.comment) {
    doc.setFontSize(11);
    doc.setFont(undefined, 'bold');
    doc.text('Class Teacher Comment:', 14, finalY);
    doc.setFont(undefined, 'normal');
    doc.setFontSize(10);
    const splitComment = doc.splitTextToSize(student.comment, 180);
    doc.text(splitComment, 14, finalY + 7);
    finalY += 7 + (splitComment.length * 5) + 8;
  }

  // Principal comment
  if (student.principalComment) {
    doc.setFontSize(11);
    doc.setFont(undefined, 'bold');
    doc.text("Principal's Comment:", 14, finalY);
    doc.setFont(undefined, 'normal');
    doc.setFontSize(10);
    const splitPrincipal = doc.splitTextToSize(student.principalComment, 180);
    doc.text(splitPrincipal, 14, finalY + 7);
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by SchoolOS - AI-Powered School Management', 14, 285);

  doc.save(`${student.name.replace(/\s+/g, '_')}_Report_Card.pdf`);
}

const avg = results => Math.round(results.reduce((a,r) => a+r.marks, 0) / results.length);
const gradeColor = g => g==='A+'||g==='A' ? 'var(--green)' : g==='B' ? 'var(--blue)' : g==='C' ? 'var(--amber)' : 'var(--red)';
const gradeBg    = g => g==='A+'||g==='A' ? 'var(--green-dim)' : g==='B' ? 'var(--blue-dim)' : g==='C' ? 'var(--amber-dim)' : 'var(--red-dim)';
const overallGrade = a => a>=80?'A+':a>=70?'A':a>=60?'B':a>=50?'C':a>=33?'D':'F';

export default function ReportCards() {
  const [students, setStudents] = useState(STUDENTS.map(s=>({...s})));
  const [selected, setSelected] = useState(null);
  const [loading, setLoading]   = useState({});

  const updateStudent = (id, updates) => {
    setStudents(prev => prev.map(s => s.id===id ? {...s,...updates} : s));
    if (selected?.id === id) setSelected(prev => ({...prev,...updates}));
  };

  const generateComment = async (id) => {
    const s = students.find(x => x.id===id);
    if (!s || loading[id]) return;
    setLoading(l => ({...l,[id]:true}));
    try {
      const prompt = `Write a professional school report card comment for ${s.name} (${s.cls}).
Results: ${s.results.map(r=>`${r.sub}: ${r.marks}/100 (${r.grade})`).join(', ')}.
Attendance: ${s.att}%. Average: ${avg(s.results)}%.
Respond with JSON only: {"teacher_comment":"2-3 warm specific sentences","principal_comment":"1-2 formal sentences"}`;
      const res = await chatWithAI(prompt, null, []);
      const text = res.data.reply.replace(/```json|```/g,'').trim();
      const parsed = JSON.parse(text);
      updateStudent(id, { generated:true, comment:parsed.teacher_comment, principalComment:parsed.principal_comment });
    } catch {
      // Fallback comment if API fails
      const a = avg(s.results);
      updateStudent(id, {
        generated: true,
        comment: `${s.name.split(' ')[0]} has demonstrated commendable effort this term with an average of ${a}%. ${a>=80?'Outstanding performance across all subjects — keep up the excellent work!':a>=60?'With continued dedication, there is great potential for further improvement.':'We encourage more consistent attendance and extra study to improve results next term.'}`,
        principalComment: `${s.name.split(' ')[0]} continues to show good character. The school encourages continued commitment to studies.`
      });
    }
    setLoading(l => ({...l,[id]:false}));
  };

  const generateAll = () => {
    students.filter(s=>!s.generated).forEach((s,i) => {
      setTimeout(() => generateComment(s.id), i*1500);
    });
  };

  const generatedCount = students.filter(s=>s.generated).length;
  const attColor = a => a>=80?'var(--green)':a>=70?'var(--amber)':'var(--red)';

  return (
    <div className="main">
      <div className="page-header">
        <div>
          <div className="page-title">AI Report Cards</div>
          <div className="page-sub">Term 2, 2026 · Generate personalised comments with Claude AI</div>
        </div>
        <div className="btn-group">
          <button className="btn">⬇ Export all PDF</button>
          <button className="btn">📢 Send to parents</button>
          <button className="btn" style={{background:'var(--purple)',color:'#fff',borderColor:'var(--purple)'}} onClick={generateAll}>
            🤖 Generate all with AI
          </button>
        </div>
      </div>

      {/* Stats */}
      <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12,marginBottom:20}}>
        {[
          {label:'Total students',value:students.length,sub:'this term',       cls:'info'},
          {label:'AI generated',  value:generatedCount,  sub:'comments ready', cls:'up'},
          {label:'Pending',       value:students.length-generatedCount,sub:'awaiting generation',cls:'warn'},
          {label:'Sent to parents',value:0,             sub:'this term',       cls:''},
        ].map(m=>(
          <div key={m.label} style={{background:'var(--bg2)',border:'1px solid var(--border)',borderRadius:12,padding:'14px 16px'}}>
            <div style={{fontSize:11,color:'var(--text3)',textTransform:'uppercase',letterSpacing:'.04em',marginBottom:4}}>{m.label}</div>
            <div style={{fontSize:20,fontWeight:600,color:'var(--text)'}}>{m.value}</div>
            <div className={m.cls} style={{fontSize:10,marginTop:3}}>{m.sub}</div>
          </div>
        ))}
      </div>

      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>

        {/* Student list */}
        <div style={{display:'flex',flexDirection:'column',gap:14}}>
          <div style={{background:'var(--bg2)',border:'1px solid var(--border)',borderRadius:14,padding:18}}>
            <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:14}}>
              <span style={{fontSize:14,fontWeight:600,color:'var(--text)'}}>Select student</span>
              <select style={{padding:'6px 10px',border:'1px solid var(--border)',borderRadius:8,background:'var(--bg3)',color:'var(--text2)',fontSize:12,outline:'none'}}>
                <option>All classes</option><option>Class 8</option><option>Class 9</option><option>Class 7</option>
              </select>
            </div>
            {students.map(s=>(
              <div key={s.id} onClick={()=>setSelected(s)}
                style={{display:'flex',alignItems:'center',gap:10,padding:'10px 12px',borderRadius:10,cursor:'pointer',transition:'all .15s',marginBottom:6,border:`1px solid ${selected?.id===s.id?'var(--blue)':'transparent'}`,background:selected?.id===s.id?'var(--blue-dim)':'transparent'}}
                onMouseEnter={e=>{ if(selected?.id!==s.id) e.currentTarget.style.background='var(--bg3)'; }}
                onMouseLeave={e=>{ if(selected?.id!==s.id) e.currentTarget.style.background='transparent'; }}>
                <div style={{width:36,height:36,borderRadius:10,background:s.avBg,color:s.avColor,display:'flex',alignItems:'center',justifyContent:'center',fontSize:13,fontWeight:700,flexShrink:0}}>{s.initials}</div>
                <div style={{flex:1}}>
                  <div style={{fontSize:13,fontWeight:500,color:'var(--text)'}}>{s.name}</div>
                  <div style={{fontSize:11,color:'var(--text3)',marginTop:2}}>{s.id} · {s.cls}</div>
                </div>
                <div style={{textAlign:'right'}}>
                  {s.generated
                    ? <span className="badge badge-green">✓ Ready</span>
                    : loading[s.id]
                    ? <span className="badge badge-blue">Generating…</span>
                    : <span className="badge badge-amber">Pending</span>}
                  <div style={{fontSize:10,color:'var(--text3)',marginTop:3}}>Avg: {avg(s.results)}%</div>
                </div>
              </div>
            ))}
          </div>

          {/* Bulk panel */}
          <div style={{background:'var(--bg2)',border:'1px solid var(--border)',borderRadius:14,padding:18}}>
            <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:14}}>
              <span style={{fontSize:14,fontWeight:600,color:'var(--text)'}}>Bulk generation</span>
              <span className="badge badge-purple">AI powered</span>
            </div>
            {students.map(s=>(
              <div key={s.id} style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'10px 14px',borderRadius:10,background:'var(--bg3)',marginBottom:8}}>
                <div style={{display:'flex',alignItems:'center',gap:10}}>
                  <div style={{width:30,height:30,borderRadius:8,background:s.avBg,color:s.avColor,display:'flex',alignItems:'center',justifyContent:'center',fontSize:11,fontWeight:700}}>{s.initials}</div>
                  <div>
                    <div style={{fontSize:13,fontWeight:500,color:'var(--text)'}}>{s.name}</div>
                    <div style={{fontSize:11,color:'var(--text3)'}}>{s.cls} · Avg {avg(s.results)}%</div>
                  </div>
                </div>
                <span style={{fontSize:18}}>{loading[s.id]?'⏳':s.generated?'✅':'⏳'}</span>
              </div>
            ))}
            <button onClick={generateAll}
              style={{width:'100%',marginTop:12,padding:10,borderRadius:8,background:'var(--purple)',color:'#fff',border:'none',fontSize:13,fontWeight:600,cursor:'pointer'}}>
              🤖 Generate all remaining with AI ↗
            </button>
          </div>
        </div>

        {/* Report preview */}
        <div style={{background:'var(--bg2)',border:'1px solid var(--border)',borderRadius:14,overflow:'hidden'}}>
          <div style={{padding:'20px 24px',background:'linear-gradient(135deg,#1E3A5F,#2E1065)',borderBottom:'1px solid var(--border)'}}>
            <div style={{fontSize:11,color:'#8B9BB8',textTransform:'uppercase',letterSpacing:'.08em',marginBottom:4}}>Lakefield Global School · Dhaka</div>
            <div style={{fontSize:18,fontWeight:700,color:'#F0F4FF',marginBottom:2}}>Student Report Card</div>
            <div style={{fontSize:12,color:'#8B9BB8'}}>Term 2 · Academic Year 2025–2026</div>
          </div>

          <div style={{padding:'20px 24px'}}>
            {!selected ? (
              <div style={{textAlign:'center',padding:'40px',color:'var(--text3)'}}>
                <div style={{fontSize:32,marginBottom:12}}>📋</div>
                <div style={{fontSize:14,fontWeight:500,color:'var(--text2)',marginBottom:8}}>Select a student</div>
                <div style={{fontSize:12}}>Click any student to preview their report card and generate AI comments.</div>
              </div>
            ) : (
              <>
                {/* Student info */}
                <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:12,marginBottom:20,paddingBottom:16,borderBottom:'1px solid var(--border)'}}>
                  {[{l:'Student name',v:selected.name},{l:'Class',v:selected.cls},{l:'Roll',v:selected.roll},{l:'Student ID',v:selected.id},{l:'Attendance',v:`${selected.att}%`,c:attColor(selected.att)},{l:'Overall grade',v:`${overallGrade(avg(selected.results))} (${avg(selected.results)}%)`,c:gradeColor(overallGrade(avg(selected.results)))}].map(x=>(
                    <div key={x.l} style={{background:'var(--bg3)',borderRadius:8,padding:'10px 12px'}}>
                      <div style={{fontSize:10,color:'var(--text3)',textTransform:'uppercase',letterSpacing:'.04em',marginBottom:3}}>{x.l}</div>
                      <div style={{fontSize:13,fontWeight:500,color:x.c||'var(--text)'}}>{x.v}</div>
                    </div>
                  ))}
                </div>

                {/* Results table */}
                <table style={{width:'100%',borderCollapse:'collapse',fontSize:12,marginBottom:20}}>
                  <thead>
                    <tr style={{background:'var(--bg3)'}}>
                      {['Subject','Marks','Full','%','Grade','Result'].map(h=>(
                        <th key={h} style={{textAlign:'left',fontWeight:600,color:'var(--text3)',padding:'8px 12px',borderBottom:'1px solid var(--border)',fontSize:11,textTransform:'uppercase',letterSpacing:'.04em'}}>{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {selected.results.map(r=>(
                      <tr key={r.sub}>
                        <td style={{padding:'9px 12px',borderBottom:'1px solid var(--border)',fontWeight:500,color:'var(--text)'}}>{r.sub}</td>
                        <td style={{padding:'9px 12px',borderBottom:'1px solid var(--border)',color:'var(--text)'}}>{r.marks}</td>
                        <td style={{padding:'9px 12px',borderBottom:'1px solid var(--border)',color:'var(--text3)'}}>{r.full}</td>
                        <td style={{padding:'9px 12px',borderBottom:'1px solid var(--border)',color:'var(--text)'}}>{Math.round(r.marks/r.full*100)}%</td>
                        <td style={{padding:'9px 12px',borderBottom:'1px solid var(--border)'}}>
                          <div style={{width:28,height:28,borderRadius:8,background:gradeBg(r.grade),color:gradeColor(r.grade),display:'flex',alignItems:'center',justifyContent:'center',fontSize:11,fontWeight:700}}>{r.grade}</div>
                        </td>
                        <td style={{padding:'9px 12px',borderBottom:'1px solid var(--border)',color:r.marks>=33?'var(--green)':'var(--red)',fontSize:11}}>{r.marks>=33?'Pass':'Fail'}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>

                {/* Teacher comment */}
                <div style={{background:'var(--bg3)',border:'1px solid var(--border2)',borderRadius:10,padding:14,marginBottom:12}}>
                  <div style={{fontSize:10,color:'var(--blue)',fontWeight:600,textTransform:'uppercase',letterSpacing:'.06em',marginBottom:8,display:'flex',alignItems:'center',gap:6}}>
                    🤖 AI Class Teacher Comment
                  </div>
                  {loading[selected.id] ? (
                    <div style={{fontSize:12,color:'var(--text3)',display:'flex',alignItems:'center',gap:8}}>
                      <span>⏳</span> Claude AI is writing the comment…
                    </div>
                  ) : selected.generated && selected.comment ? (
                    <div style={{fontSize:12,color:'var(--text2)',lineHeight:1.7,fontStyle:'italic'}}>"{selected.comment}"</div>
                  ) : (
                    <div style={{display:'flex',alignItems:'center',justifyContent:'space-between'}}>
                      <div style={{fontSize:12,color:'var(--text3)'}}>No comment generated yet</div>
                      <button onClick={()=>generateComment(selected.id)} style={{padding:'6px 14px',borderRadius:8,background:'var(--purple)',color:'#fff',border:'none',fontSize:12,cursor:'pointer',fontWeight:500}}>Generate ↗</button>
                    </div>
                  )}
                </div>

                {/* Principal comment */}
                <div style={{background:'var(--bg3)',border:'1px solid var(--border)',borderRadius:10,padding:14,marginBottom:16}}>
                  <div style={{fontSize:10,color:'var(--text3)',fontWeight:600,textTransform:'uppercase',letterSpacing:'.06em',marginBottom:8}}>🏫 Principal's Comment</div>
                  {selected.generated && selected.principalComment ? (
                    <div style={{fontSize:12,color:'var(--text2)',lineHeight:1.7,fontStyle:'italic'}}>"{selected.principalComment}"</div>
                  ) : (
                    <div style={{fontSize:12,color:'var(--text3)'}}>Will be generated with teacher comment</div>
                  )}
                </div>

                {/* Action buttons */}
                <div style={{display:'flex',gap:8}}>
                  <button onClick={()=>generateComment(selected.id)} disabled={loading[selected.id]}
                    style={{flex:1,padding:10,borderRadius:8,background:'var(--purple)',color:'#fff',border:'none',fontSize:13,fontWeight:600,cursor:'pointer',opacity:loading[selected.id]?0.6:1}}>
                    {loading[selected.id]?'Generating…':selected.generated?'🔄 Regenerate':'🤖 Generate AI comment'}
                  </button>
                  <button onClick={()=>exportToPDF(selected, avg(selected.results), overallGrade(avg(selected.results)))} style={{flex:1,padding:10,borderRadius:8,background:'var(--bg3)',color:'var(--text2)',border:'1px solid var(--border)',fontSize:13,cursor:'pointer'}}>
                    ⬇ Export PDF
                  </button>
                </div>
              </>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
